// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAKnT5cPks-NXn89CkElZF1TofOufVzMc',
    appId: '1:716491318181:web:fed5ac0e26a2e9251efe4c',
    messagingSenderId: '716491318181',
    projectId: 'churchapp-38c86',
    authDomain: 'churchapp-38c86.firebaseapp.com',
    databaseURL: 'https://churchapp-38c86-default-rtdb.firebaseio.com',
    storageBucket: 'churchapp-38c86.firebasestorage.app',
    measurementId: 'G-PTT8YZZ09Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwJj2Wd9pRQRmV3nVYcCcdJya20_2VyOY',
    appId: '1:716491318181:android:e1eeaa1576879c911efe4c',
    messagingSenderId: '716491318181',
    projectId: 'churchapp-38c86',
    databaseURL: 'https://churchapp-38c86-default-rtdb.firebaseio.com',
    storageBucket: 'churchapp-38c86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmw6PDHbScfh_jvNjsbeg17-evtsuwCR4',
    appId: '1:716491318181:ios:3dea10e49b0637d11efe4c',
    messagingSenderId: '716491318181',
    projectId: 'churchapp-38c86',
    databaseURL: 'https://churchapp-38c86-default-rtdb.firebaseio.com',
    storageBucket: 'churchapp-38c86.firebasestorage.app',
    iosClientId: '716491318181-qp44q5n652vn5q8dhagoh75s8b9hkllj.apps.googleusercontent.com',
    iosBundleId: 'com.example.churchapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmw6PDHbScfh_jvNjsbeg17-evtsuwCR4',
    appId: '1:716491318181:ios:3dea10e49b0637d11efe4c',
    messagingSenderId: '716491318181',
    projectId: 'churchapp-38c86',
    databaseURL: 'https://churchapp-38c86-default-rtdb.firebaseio.com',
    storageBucket: 'churchapp-38c86.firebasestorage.app',
    iosClientId: '716491318181-qp44q5n652vn5q8dhagoh75s8b9hkllj.apps.googleusercontent.com',
    iosBundleId: 'com.example.churchapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAKnT5cPks-NXn89CkElZF1TofOufVzMc',
    appId: '1:716491318181:web:f8c81bc3972a88811efe4c',
    messagingSenderId: '716491318181',
    projectId: 'churchapp-38c86',
    authDomain: 'churchapp-38c86.firebaseapp.com',
    databaseURL: 'https://churchapp-38c86-default-rtdb.firebaseio.com',
    storageBucket: 'churchapp-38c86.firebasestorage.app',
    measurementId: 'G-P3VJTRMHQ2',
  );

}